# Generated by Django 3.1.7 on 2021-03-08 03:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(db_index=True, max_length=255, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='password')),
                ('phone', models.CharField(db_index=True, default=None, max_length=11, verbose_name='手机号')),
                ('email', models.CharField(db_index=True, default=None, max_length=20, verbose_name='邮箱')),
                ('role', models.CharField(db_index=True, max_length=28, verbose_name='用户角色')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommodityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('cno', models.IntegerField(default=1)),
                ('type', models.CharField(max_length=60, verbose_name='商品类型')),
                ('price', models.FloatField(default=0, verbose_name='价格')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
                'db_table': 'commodity_info',
            },
        ),
        migrations.CreateModel(
            name='OrderInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ono', models.CharField(default='2021030811173702', max_length=128)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('uno', models.IntegerField(default=0, verbose_name='用户号')),
                ('rno', models.IntegerField(default=0, verbose_name='房间号')),
                ('num', models.IntegerField(default=1, verbose_name='商品数量')),
                ('start_time', models.DateField(default=datetime.datetime.now, verbose_name='入住时间')),
                ('end_time', models.DateField(default=datetime.datetime.now, verbose_name='退房时间')),
                ('price', models.FloatField(default=0, verbose_name='消费金额')),
            ],
            options={
                'verbose_name': '订单信息表',
                'verbose_name_plural': '订单信息表',
                'db_table': 'order_info',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateField(default=datetime.datetime.now, verbose_name='入住时间')),
                ('uno', models.IntegerField(default=0, verbose_name='用户号')),
                ('rno', models.IntegerField(default=0, verbose_name='用户号')),
                ('id_card', models.CharField(default='', max_length=18, verbose_name='身份证号')),
            ],
            options={
                'verbose_name': '入住房间登记',
                'verbose_name_plural': '入住房间登记',
                'db_table': 'register',
            },
        ),
        migrations.CreateModel(
            name='RoomInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('rno', models.IntegerField(default=101)),
                ('style', models.CharField(max_length=60, verbose_name='房间类型')),
                ('dsc', models.CharField(default='', max_length=255, verbose_name='简介')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='价格')),
            ],
            options={
                'verbose_name': '房间信息',
                'verbose_name_plural': '房间信息',
                'db_table': 'room_info',
            },
        ),
        migrations.CreateModel(
            name='ROrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('order_info_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='last.orderinformation', verbose_name='订单信息表')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='last.roominfo', verbose_name='用户订购房间')),
            ],
            options={
                'verbose_name': '订单中房间信息',
                'verbose_name_plural': '订单中房间信息',
                'db_table': 'room_order',
            },
        ),
        migrations.CreateModel(
            name='COrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('c_good_num', models.IntegerField(default=1)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='last.commodityinfo', verbose_name='用户购买的商品')),
                ('order_info_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='last.orderinformation', verbose_name='订单信息表')),
            ],
            options={
                'verbose_name': '订单中商品信息',
                'verbose_name_plural': '订单中商品信息',
                'db_table': 'commodity_order',
            },
        ),
        migrations.CreateModel(
            name='BookingInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateField(default=datetime.datetime.now, verbose_name='入住时间')),
                ('end_time', models.DateField(default=datetime.datetime.now, verbose_name='退订时间')),
                ('status', models.IntegerField(choices=[(1, '已预订'), (2, '已入住'), (3, '已退房')], default=1, verbose_name='1.已预订，2.已入住，3.已退房')),
                ('deposit', models.FloatField(default=0, verbose_name='押金')),
                ('is_cancel', models.BooleanField(default=0, verbose_name='是否取消预订')),
                ('rno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='last.roominfo', verbose_name='房间编号')),
                ('uno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户编号')),
            ],
            options={
                'verbose_name': '预订房间信息',
                'verbose_name_plural': '预订房间信息',
                'db_table': 'book_info',
            },
        ),
    ]
